[package]
name = "validation-service"
version = "0.1.0"
edition = "2021"
authors = ["verse-pbc"]
description = "Location validation service for Peek communities"

[dependencies]
# Web framework
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Geolocation
geo = "0.28"

# Nostr
nostr-sdk = { version = "0.43", features = ["nip44", "nip59"] }

# Environment and config
dotenv = "0.15"
envy = "0.4"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# UUID
uuid = { version = "1.10", features = ["v4", "serde"] }

# Time
chrono = { version = "0.4", features = ["serde"] }

# Error handling
thiserror = "1.0"

# Utilities
base64 = "0.22"
rand = "0.8"

[dev-dependencies]
# Testing
axum-test = "15.0"
reqwest = { version = "0.12", features = ["json"] }
tower = { version = "0.4", features = ["util"] }

[[bin]]
name = "test_gift_wrap"
path = "src/test_gift_wrap.rs"

[[bin]]
name = "export_gift_wrap"
path = "src/export_gift_wrap.rs"

[[bin]]
name = "import_js_gift_wrap"
path = "src/import_js_gift_wrap.rs"

[[bin]]
name = "test_actual_pubkey"
path = "src/test_actual_pubkey.rs"
