services:
  # Validation service - uses communities2.nos.social relay
  validation_service:
    build:
      context: ./packages/validation-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./packages/validation-service/.env
    environment:
      # Override port for consistency
      PORT: "3001"
      # Set log level
      RUST_LOG: "debug"
    # Health check disabled - container doesn't have curl
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
