openapi: 3.0.0
info:
  title: Peek Validation Service API
  version: 0.1.0
  description: Location validation service for community joining

servers:
  - url: http://localhost:3000/api
    description: Local development
  - url: https://api.peek.app/api
    description: Production

paths:
  /validate-location:
    post:
      summary: Validate user's physical presence at community location
      operationId: validateLocation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - communityId
                - coordinates
                - accuracy
                - timestamp
                - userPubkey
              properties:
                communityId:
                  type: string
                  format: uuid
                  description: Target community ID from QR code
                coordinates:
                  type: object
                  required:
                    - latitude
                    - longitude
                  properties:
                    latitude:
                      type: number
                      minimum: -90
                      maximum: 90
                    longitude:
                      type: number
                      minimum: -180
                      maximum: 180
                accuracy:
                  type: number
                  description: Horizontal accuracy in meters
                  minimum: 0
                timestamp:
                  type: number
                  description: Unix timestamp of GPS reading
                userPubkey:
                  type: string
                  pattern: ^[a-f0-9]{64}$
                  description: User's Nostr public key
      responses:
        '200':
          description: Location validation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    enum: [true]
                  token:
                    type: string
                    description: JWT token for joining community
                  expiresAt:
                    type: number
                    description: Token expiration timestamp
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    enum: [false]
                  error:
                    type: string
                    enum:
                      - ACCURACY_TOO_LOW
                      - DISTANCE_TOO_FAR
                      - TIMESTAMP_EXPIRED
                      - INVALID_COORDINATES
                  details:
                    type: object
                    properties:
                      distance:
                        type: number
                        description: Distance from QR in meters
                      accuracy:
                        type: number
                        description: GPS accuracy in meters
                      maxDistance:
                        type: number
                        enum: [25]
                      maxAccuracy:
                        type: number
                        enum: [20]

  /verify-join:
    post:
      summary: Exchange validated token for relay group invite
      operationId: verifyJoin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: JWT token from location validation
      responses:
        '200':
          description: Join verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    enum: [true]
                  invite:
                    type: object
                    properties:
                      relay:
                        type: string
                        format: uri
                        description: Relay WebSocket URL
                      groupId:
                        type: string
                        description: NIP-29 group identifier
                      inviteCode:
                        type: string
                        description: One-time invite code for relay
        '401':
          description: Token invalid or expired
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    enum: [false]
                  error:
                    type: string
                    enum:
                      - TOKEN_EXPIRED
                      - TOKEN_INVALID
                      - TOKEN_ALREADY_USED
                      - TOKEN_SIGNATURE_INVALID

  /community/{communityId}/preview:
    get:
      summary: Get community preview information (no auth required)
      operationId: getCommunityPreview
      parameters:
        - name: communityId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Community preview data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  description:
                    type: string
                  memberCount:
                    type: number
                  createdAt:
                    type: number
                    description: Unix timestamp
                  location:
                    type: object
                    properties:
                      city:
                        type: string
                        description: Coarse location (city name)
                      country:
                        type: string
                        description: Country code
        '404':
          description: Community not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [COMMUNITY_NOT_FOUND]

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object