apiVersion: v1
kind: Service
metadata:
  name: peek-pwa-client
  namespace: peek
  labels:
    app.kubernetes.io/name: peek-pwa-client
    app.kubernetes.io/part-of: peek
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: peek-pwa-client