import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Alert, AlertDescription } from './ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Checkbox } from './ui/checkbox';
import { AlertCircle, Zap, Copy, AlertTriangle, Cloud, Shield, KeyRound } from 'lucide-react';
import { useToast } from '@/hooks/useToast';
import { useIsMobile } from '@/hooks/useIsMobile';
import { useTranslation } from 'react-i18next';
import { generateNostrConnectURI } from '@/lib/nostr-identity';

interface IdentityModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onImport: (nsec: string, shouldMigrate?: boolean) => void;
  onExtension?: () => void;
  onBunker?: (uri: string, options?: { clientSecretKey?: string; isNostrConnect?: boolean }) => void;
  mode: 'upgrade' | 'switch';
  hasBackedUpNsec?: boolean;
  currentNsec?: string;
  isAutoGenerated?: boolean;
  hasJoinedCommunities?: boolean;
  isUsingExtension?: boolean;
}

export const IdentityModal: React.FC<IdentityModalProps> = ({
  open,
  onOpenChange,
  onImport,
  onExtension,
  onBunker,
  mode,
  hasBackedUpNsec = false,
  currentNsec,
  isAutoGenerated = false,
  hasJoinedCommunities = false,
  isUsingExtension = false,
}) => {
  const { t, i18n } = useTranslation();
  const { toast } = useToast();
  const isMobile = useIsMobile();
  const [nsecInput, setNsecInput] = useState('');
  const [bunkerUri, setBunkerUri] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [bunkerError, setBunkerError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'import' | 'extension' | 'bunker'>('import');
  const [keepCommunities, setKeepCommunities] = useState(true);
  const [showBackupWarning, setShowBackupWarning] = useState(false);
  const [hasConfirmedBackup, setHasConfirmedBackup] = useState(false);

  // Bunker-specific state
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [nostrConnectUri, setNostrConnectUri] = useState<string | null>(null);
  const [nostrConnectData, setNostrConnectData] = useState<{
    uri: string;
    clientSecretKey: string;
    clientPubkey: string;
    secret: string;
    relay: string;
  } | null>(null);
  const [isWaitingForConnection, setIsWaitingForConnection] = useState(false);

  const isUpgradeMode = mode === 'upgrade';
  const showMigrationChoice = isUpgradeMode && isAutoGenerated && hasJoinedCommunities;
  const hasExtension = typeof window !== 'undefined' && !!window.nostr;
  const showExtensionTab = hasExtension && !isUsingExtension && !isMobile; // Hide extension tab on mobile

  const handleCopyCurrentNsec = () => {
    if (!currentNsec) return;
    navigator.clipboard.writeText(currentNsec);
    setHasConfirmedBackup(true);
    toast({ title: "Secret key copied!", description: "Store this safely to return to your communities later." });
  };

  const handleCheckboxChange = (checked: boolean | 'indeterminate') => {
    const isChecked = checked === true;
    setKeepCommunities(isChecked);
    // If unchecking and haven't backed up yet, show warning
    if (!isChecked && !hasConfirmedBackup && !hasBackedUpNsec) {
      setShowBackupWarning(true);
    } else {
      setShowBackupWarning(false);
    }
  };

  const handleImport = React.useCallback(() => {
    console.log('[IdentityModal] handleImport called with nsec:', nsecInput.substring(0, 10) + '...');

    if (!nsecInput.trim()) {
      setError('Please enter your nsec key');
      return;
    }

    if (!nsecInput.startsWith('nsec1')) {
      setError('Invalid nsec format - must start with nsec1');
      return;
    }

    try {
      console.log('[IdentityModal] Calling onImport with shouldMigrate:', keepCommunities);
      onImport(nsecInput, keepCommunities);
      console.log('[IdentityModal] onImport completed successfully');
    } catch (err) {
      console.error('[IdentityModal] onImport failed:', err);
      setError('Invalid nsec key - please check and try again');
    }
  }, [nsecInput, onImport, keepCommunities]);

  const handleExtension = () => {
    if (onExtension) {
      onExtension();
      onOpenChange(false);
    }
  };

  const handleBunker = React.useCallback(() => {
    if (!bunkerUri.trim()) {
      setBunkerError('Please enter a bunker URI');
      return;
    }

    if (!bunkerUri.startsWith('bunker://')) {
      setBunkerError('Invalid bunker URI format. Must start with bunker://');
      return;
    }

    try {
      if (onBunker) {
        onBunker(bunkerUri);
        onOpenChange(false);
      }
    } catch (err) {
      console.error('[IdentityModal] onBunker failed:', err);
      setBunkerError('Failed to connect to bunker. Please check the URI.');
    }
  }, [bunkerUri, onBunker, onOpenChange]);

  const handleGenerateNostrConnect = async () => {
    try {
      const data = generateNostrConnectURI();
      setNostrConnectUri(data.uri);
      setNostrConnectData(data);
      setBunkerError(null);
      setIsWaitingForConnection(true);

      console.log('[IdentityModal] Generated nostrconnect:// with nsec.app format');

      // Start listening for connection
      if (onBunker) {
        await onBunker(data.uri, {
          clientSecretKey: data.clientSecretKey,
          isNostrConnect: true
        });
      }
    } catch (err) {
      console.error('[IdentityModal] Failed:', err);
      setBunkerError(err instanceof Error ? err.message : 'Connection failed');
      setIsWaitingForConnection(false);
    }
  };

  const handleCopyNostrConnect = () => {
    if (!nostrConnectUri) return;
    navigator.clipboard.writeText(nostrConnectUri);
    toast({ title: "Copied!", description: "Paste into nsec.app" });
  };

  // Set default tab based on platform and available options
  React.useEffect(() => {
    if (isMobile) {
      setActiveTab('bunker'); // Default to bunker on mobile
    } else if (showExtensionTab) {
      setActiveTab('extension'); // Default to extension on desktop if available
    } else {
      setActiveTab('import'); // Fallback to import
    }
  }, [isMobile, showExtensionTab]);

  // Offer to import or use extension
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{t('identity_modal.title')}</DialogTitle>
          <DialogDescription className="space-y-2">
            <span>
              {mode === 'upgrade' && hasJoinedCommunities
                ? t('identity_modal.description_with_migration')
                : t('identity_modal.description')
              }
            </span>
            <a
              href={`https://nostr.how/${i18n.language}/get-started`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-coral hover:underline inline-flex items-center gap-1"
            >
              {t('identity_modal.new_to_nostr_link')} →
            </a>
          </DialogDescription>
        </DialogHeader>

        {/* Migration choice for auto-generated users with communities */}
        {showMigrationChoice && (
          <div className="space-y-3 p-4 border rounded-lg bg-muted/50">
            <div className="flex items-start space-x-3">
              <Checkbox
                id="keep-communities"
                checked={keepCommunities}
                onCheckedChange={handleCheckboxChange}
                className="mt-0.5"
              />
              <div className="flex-1 space-y-1">
                <label
                  htmlFor="keep-communities"
                  className="text-sm font-medium cursor-pointer leading-tight"
                >
                  {t('identity_modal.migration.keep_communities')}
                </label>
                <p className="text-xs text-muted-foreground">
                  {t('identity_modal.migration.keep_description')}
                </p>
              </div>
            </div>

            {/* Inline backup warning when unchecked */}
            {!keepCommunities && (
              <div className="space-y-3 pt-3 border-t">
                <div className="flex gap-2 text-destructive">
                  <AlertTriangle className="h-4 w-4 flex-shrink-0 mt-0.5" />
                  <div className="text-sm space-y-2">
                    <div className="font-medium">{t('identity_modal.migration.save_key_warning')}</div>
                    <div>
                      {t('identity_modal.migration.save_key_reason')}
                    </div>
                  </div>
                </div>
                {currentNsec && (
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full"
                    onClick={handleCopyCurrentNsec}
                  >
                    <Copy className="mr-2 h-4 w-4" />
                    {hasConfirmedBackup ? t('identity_modal.migration.key_copied') : t('identity_modal.migration.copy_key')}
                  </Button>
                )}
                <p className="text-xs text-muted-foreground">
                  {t('identity_modal.migration.store_safely')}
                </p>
              </div>
            )}
          </div>
        )}

        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as 'import' | 'extension' | 'bunker')}>
          <TabsList className={`grid w-full ${showExtensionTab ? 'grid-cols-3' : 'grid-cols-2'}`}>
            {showExtensionTab && (
              <TabsTrigger value="extension">
                <Shield className="w-4 h-4 mr-2" />
                {t('identity_modal.tabs.extension')}
              </TabsTrigger>
            )}
            <TabsTrigger value="bunker">
              <Cloud className="w-4 h-4 mr-2" />
              {t('identity_modal.tabs.key_manager')}
            </TabsTrigger>
            <TabsTrigger value="import">
              <KeyRound className="w-4 h-4 mr-2" />
              {t('identity_modal.tabs.paste_key')}
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="import" className="space-y-4">
            <div className="space-y-3">
              <div className="space-y-2">
                <p className="text-sm font-medium">{t('identity_modal.paste_key.title')}</p>
                <p className="text-xs text-muted-foreground">
                  {t('identity_modal.paste_key.description')}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="nsec">{t('identity_modal.paste_key.input_label')}</Label>
                <Input
                  id="nsec"
                  type="password"
                  placeholder="nsec1..."
                  value={nsecInput}
                  onChange={(e) => {
                    setNsecInput(e.target.value);
                    setError(null);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') handleImport();
                  }}
                />
              </div>

              {error && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription className="space-y-2">
                  <p className="font-medium">{t('identity_modal.paste_key.security_notice')}</p>
                  <p className="text-xs">
                    {t('identity_modal.paste_key.security_warning')}
                  </p>
                  <div className="text-xs space-y-1">
                    <p>✓ {t('identity_modal.paste_key.best_for')}</p>
                    <p>✗ {t('identity_modal.paste_key.avoid')}</p>
                  </div>
                </AlertDescription>
              </Alert>

              <div className="space-y-2">
                <p className="text-xs text-muted-foreground">
                  🔐 {t('identity_modal.paste_key.more_secure')}
                </p>
                <a
                  href={`https://nostr.how/${i18n.language}/get-started`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-coral hover:underline inline-flex items-center gap-1"
                >
                  {t('identity_modal.paste_key.new_to_nostr')} →
                </a>
              </div>
            </div>
            
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                {t('identity_modal.cancel')}
              </Button>
              <Button
                type="button"
                onClick={handleImport}
                disabled={showBackupWarning && !hasConfirmedBackup}
              >
                {hasJoinedCommunities
                  ? (keepCommunities ? t('identity_modal.paste_key.upgrade_keep') : t('identity_modal.paste_key.switch_fresh'))
                  : t('identity_modal.paste_key.switch_account')
                }
              </Button>
            </DialogFooter>
          </TabsContent>

          <TabsContent value="extension" className="space-y-4">
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">
                {t('identity_modal.extension.description')}
              </p>

              <Alert>
                <Zap className="h-4 w-4" />
                <AlertDescription>
                  {t('identity_modal.extension.security_note')}
                </AlertDescription>
              </Alert>

              {!window.nostr && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    {t('identity_modal.extension.not_detected')}
                  </AlertDescription>
                </Alert>
              )}
            </div>

            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                {t('identity_modal.cancel')}
              </Button>
              <Button
                type="button"
                onClick={handleExtension}
                disabled={!window.nostr || !onExtension}
              >
                <Zap className="mr-2 h-4 w-4" />
                {t('identity_modal.extension.connect_button')}
              </Button>
            </DialogFooter>
          </TabsContent>

          <TabsContent value="bunker" className="space-y-4">
            <div className="space-y-3">
              <div>
                <p className="font-medium text-sm">{t('identity_modal.key_manager.title')}</p>
                <p className="text-xs text-muted-foreground mt-1">
                  {t('identity_modal.key_manager.description')}
                </p>
              </div>

              {!showAdvanced ? (
                // Default: Generate nostrconnect (client-initiated)
                !nostrConnectUri ? (
                  <div className="space-y-3">
                    <p className="text-xs text-muted-foreground">
                      Peek will create a connection code for you
                    </p>

                    <Button onClick={handleGenerateNostrConnect} className="w-full">
                      <Cloud className="mr-2 h-4 w-4" />
                      Generate Connection Code
                    </Button>

                    <div className="flex justify-end">
                      <button
                        onClick={() => setShowAdvanced(true)}
                        className="text-xs text-muted-foreground hover:text-foreground hover:underline"
                      >
                        Advanced: I have a bunker URL →
                      </button>
                    </div>
                  </div>
                ) : (
                  // After generating
                  <div className="space-y-3">
                    {isWaitingForConnection && (
                      <p className="text-sm">⏳ Waiting for approval...</p>
                    )}

                    <div>
                      <div className="flex justify-between mb-1">
                        <Label className="text-sm">Connection code</Label>
                        <Button onClick={handleCopyNostrConnect} size="sm" variant="ghost">
                          <Copy className="w-3 h-3 mr-1" />
                          Copy
                        </Button>
                      </div>
                      <Input
                        value={nostrConnectUri}
                        readOnly
                        className="font-mono text-xs"
                        onClick={(e) => e.currentTarget.select()}
                      />
                    </div>

                    <p className="text-xs text-muted-foreground">
                      Paste into nsec.app → Connect App, then approve
                    </p>

                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        setNostrConnectUri(null);
                        setNostrConnectData(null);
                        setIsWaitingForConnection(false);
                      }}
                    >
                      Start Over
                    </Button>
                  </div>
                )
              ) : (
                // Advanced: Paste bunker URL (remote-initiated)
                <div className="space-y-3">
                  <button
                    onClick={() => setShowAdvanced(false)}
                    className="text-xs text-blue-600 hover:underline"
                  >
                    ← Back to generate
                  </button>

                  <div className="space-y-2">
                    <Label htmlFor="bunkerUri">Paste bunker URL from your key manager</Label>
                    <Input
                      id="bunkerUri"
                      type="text"
                      placeholder="bunker://..."
                      value={bunkerUri}
                      onChange={(e) => {
                        setBunkerUri(e.target.value);
                        setBunkerError(null);
                      }}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') handleBunker();
                      }}
                      className="font-mono text-xs"
                    />
                    <p className="text-xs text-muted-foreground">
                      {t('identity_modal.key_manager.input_hint')}
                    </p>
                  </div>

                  <details className="text-xs">
                    <summary className="cursor-pointer text-muted-foreground hover:text-foreground">
                      {t('identity_modal.key_manager.how_to_get')}
                    </summary>
                    <ol className="mt-2 space-y-1 list-decimal list-inside text-muted-foreground">
                      <li><a href="https://nsec.app" target="_blank" className="text-blue-600 hover:underline">{t('identity_modal.key_manager.steps.1')}</a></li>
                      <li>{t('identity_modal.key_manager.steps.2')}</li>
                      <li>{t('identity_modal.key_manager.steps.3')}</li>
                      <li>{t('identity_modal.key_manager.steps.4')}</li>
                      <li>{t('identity_modal.key_manager.steps.5')}</li>
                      <li>{t('identity_modal.key_manager.steps.6')}</li>
                    </ol>
                    <p className="mt-2 text-muted-foreground">
                      💡 {t('identity_modal.key_manager.popup_blocked')}
                    </p>
                  </details>

                  <DialogFooter>
                    <Button variant="outline" onClick={() => onOpenChange(false)}>
                      {t('identity_modal.cancel')}
                    </Button>
                    <Button
                      onClick={handleBunker}
                      disabled={!bunkerUri.trim()}
                      className="flex-1"
                    >
                      <Cloud className="mr-2 h-4 w-4" />
                      {t('identity_modal.key_manager.connect_button')}
                    </Button>
                  </DialogFooter>
                </div>
              )}
            </div>

            {bunkerError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{bunkerError}</AlertDescription>
              </Alert>
            )}
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};