import { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useSeoMeta } from '@unhead/react';
import { useNostrContext } from '@/hooks/useNostrContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  MapPin,
  Users,
  MessageSquare,
  Clock,
  ChevronRight,
  Loader2,
  UserCircle,
  Crown,
  Sparkles,
  Plus,
} from 'lucide-react';
import { useToast } from '@/hooks/useToast';
import { useNostrLogin } from '../lib/nostr-identity';
import { useRelayManager } from '../contexts/RelayContext';
import { useTranslation } from 'react-i18next';
import { UserIdentityButton } from '@/components/UserIdentityButton';
import { IOSPWAImportPrompt } from '@/components/IOSPWAImportPrompt';
import { LanguageSelector } from '@/components/LanguageSelector';
import { isIOS, isPWA } from '@/lib/platform';

interface Community {
  communityId: string;
  name: string;
  memberCount: number;
  lastActivity?: number;
  createdAt?: number;
  isAdmin: boolean;
  unreadCount?: number;
  picture?: string;
  location?: {
    latitude: number;
    longitude: number;
  };
  joinedAt?: number;
}

const Home = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { user } = useNostrContext();
  const { pubkey, login, identity } = useNostrLogin();
  const { toast } = useToast();
  const { groupManager, relayManager, connected } = useRelayManager();
  const { t } = useTranslation();
  const [communities, setCommunities] = useState<Community[]>([]);
  const [loading, setLoading] = useState(true);

  // Show import prompt for iOS PWA users with auto-generated identity
  // This catches fresh PWA installs that auto-created an anonymous identity
  const shouldShowImportPrompt = isIOS() && isPWA() && identity?.isAutoGenerated && !loading;
  const [rejoinMessage, setRejoinMessage] = useState<string | null>(null);

  // Dev mode detection - show "Create Dev Test Community" button when ?dev=true
  const urlParams = useMemo(() => new URLSearchParams(window.location.search), []);
  const isDevMode = urlParams.get('dev') === 'true';

  useSeoMeta({
    title: 'Peek - Location-Based Communities',
    description: 'Connect with people at physical locations through QR codes',
  });

  // Check for navigation state message
  useEffect(() => {
    if (location.state?.message) {
      setRejoinMessage(location.state.message);
      window.history.replaceState({}, document.title);
    }
  }, [location.state]);

  // Auto-center map on user location on load - DISABLED (map is hidden)
  // useEffect(() => {
  //   if (navigator.geolocation) {
  //     navigator.geolocation.getCurrentPosition(
  //       (position) => {
  //         const userLocation = new LatLng(
  //           position.coords.latitude,
  //           position.coords.longitude
  //         );
  //         setMapCenter(userLocation);
  //         setFlyToLocation(userLocation);
  //         console.log('[Home] Auto-centered map on user location:', userLocation);
  //       },
  //       (error) => {
  //         console.warn('[Home] Could not get user location:', error.message);
  //         // Keep default SF coordinates if location access denied
  //       },
  //       {
  //         enableHighAccuracy: true,
  //         timeout: 5000,
  //         maximumAge: 0
  //       }
  //     );
  //   }
  // }, []); // Run once on mount

  // Load discovery map - DISABLED (map is hidden)
  // useEffect(() => {
  //   const loadDiscoveryMap = async () => {
  //     try {
  //       const service = new DiscoveryService(RELAY_URL);
  //       discoveryServiceRef.current = service;

  //       const map = await service.fetchDiscoveryMap();
  //       setDiscoveryMap(map);

  //       // Subscribe to updates
  //       const unsubscribe = service.subscribeToDiscoveryUpdates((updatedMap) => {
  //         setDiscoveryMap(updatedMap);
  //       });

  //       return () => {
  //         unsubscribe();
  //       };
  //     } catch (error) {
  //       console.error('Failed to load discovery map:', error);
  //     }
  //   };

  //   loadDiscoveryMap();

  //   return () => {
  //     if (discoveryServiceRef.current) {
  //       discoveryServiceRef.current.close();
  //     }
  //   };
  // }, []);

  // Fetch user's communities (re-runs on navigation to home)
  useEffect(() => {
    // Wait for relay connection before fetching
    if (!connected || !groupManager || !relayManager) {
      return;
    }

    let isActive = true;
    let fetchCount = 0;

    const fetchCommunities = async () => {
      if (!isActive || !groupManager || !relayManager) return;
      fetchCount++;

      // Only show loading spinner if we have no communities yet
      // This prevents flicker on reconnect - React diffs will handle updates
      if (communities.length === 0) {
        setLoading(true);
      }

      try {
        console.log('[Home] Fetching communities using NIP-29 events...');

        // Use GroupManager to get communities from NIP-29 events
        const userGroups = await groupManager.getUserGroups();
        console.log(`[Home] Found ${userGroups.length} communities from NIP-29 events`);

        // Batch fetch last activity for all groups in a single query
        const nip29GroupIds = userGroups.map(g => g.nip29GroupId);
        const lastActivityMap = await relayManager.getMultipleGroupsLastActivity(nip29GroupIds);

        // Convert to Community format for the UI
        const userCommunities: Community[] = userGroups.map(group => {
          // Try to get location from localStorage as fallback for UI
          const joinedGroups = JSON.parse(localStorage.getItem('joinedGroups') || '[]');
          const cachedGroupInfo = joinedGroups.find((g: { communityId: string }) => g.communityId === group.communityId);

          // Get last activity from batched results
          const lastActivity = lastActivityMap.get(group.nip29GroupId);

          return {
            communityId: group.communityId,
            name: group.name,
            memberCount: group.memberCount,
            isAdmin: group.isAdmin,
            joinedAt: cachedGroupInfo?.joinedAt || Date.now() / 1000,
            lastActivity: lastActivity || undefined,
            createdAt: group.metadata?.createdAt,
            picture: group.metadata?.picture,
            location: cachedGroupInfo?.location
          };
        });

        // Sort by last activity (most recent first), fallback to createdAt, then joinedAt
        userCommunities.sort((a, b) => {
          const aTime = a.lastActivity || a.createdAt || a.joinedAt || 0;
          const bTime = b.lastActivity || b.createdAt || b.joinedAt || 0;
          return bTime - aTime;
        });

        if (isActive) {
          console.log('[Home] Setting communities from NIP-29 events:', userCommunities);
          setCommunities(userCommunities);
        }
      } catch (error) {
        console.error('[Home] Error fetching communities from NIP-29:', error);
        if (fetchCount === 1 && error && !(error instanceof TypeError && error.message?.includes('fetchEvents'))) {
          toast({
            title: 'Error',
            description: 'Failed to load your communities',
            variant: 'destructive'
          });
        }
        if (isActive) {
          setCommunities([]);
        }
      } finally {
        if (isActive) {
          setLoading(false);
        }
      }
    };

    fetchCommunities();

    return () => {
      isActive = false;
    };
  }, [connected, groupManager, relayManager, toast, location.pathname]); // communities.length intentionally omitted - only check on connection change

  const formatTimeAgo = (timestamp?: number) => {
    if (!timestamp) return t('common.time.never');

    const now = Date.now() / 1000;
    const diff = now - timestamp;

    if (diff < 60) return t('common.time.just_now');
    if (diff < 3600) return t('common.time.minutes_ago', { count: Math.floor(diff / 60) });
    if (diff < 86400) return t('common.time.hours_ago', { count: Math.floor(diff / 3600) });
    if (diff < 604800) return t('common.time.days_ago', { count: Math.floor(diff / 86400) });
    return new Date(timestamp * 1000).toLocaleDateString();
  };

  const handleCommunityClick = (communityId: string) => {
    navigate(`/c/${communityId}`);
  };

  const handleCreateTestCommunity = useCallback(() => {
    const uuid = crypto.randomUUID();
    navigate(`/c/${uuid}?dev=true`);
  }, [navigate]);

  if (!user || !pubkey) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Card className="w-full max-w-md bg-card backdrop-blur shadow-2xl border-0">
          <CardHeader className="text-center pb-4">
            <div className="mx-auto w-20 h-20 bg-coral/10 rounded-full flex items-center justify-center mb-4">
              <MapPin className="h-10 w-10 text-coral" />
            </div>
            <CardTitle className="text-3xl font-rubik">{t('home.welcome.title')}</CardTitle>
            <CardDescription className="text-base">
              {t('home.welcome.subtitle')}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Alert className="border-coral/20 bg-coral/5 dark:bg-coral/10 dark:border-coral/30">
              <Sparkles className="h-4 w-4 text-coral" />
              <AlertDescription className="dark:text-foreground">
                {t('home.welcome.scan_prompt')}
              </AlertDescription>
            </Alert>

            <Button
              onClick={login}
              className="w-full bg-coral hover:bg-coral/90 text-white font-semibold py-6 text-lg rounded-full"
              size="lg"
            >
              <UserCircle className="mr-2 h-5 w-5" />
              {t('home.welcome.login_button')}
            </Button>

            <p className="text-xs text-center text-muted-foreground">
              {t('home.welcome.login_hint')}
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Show import prompt for iOS PWA users without identity
  if (shouldShowImportPrompt) {
    return <IOSPWAImportPrompt />
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Simplified Header */}
      <header className="bg-card/90 backdrop-blur border-b border-border sticky top-0 z-50">
        <div className="container mx-auto px-3 sm:px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-9 h-9 sm:w-10 sm:h-10 bg-coral rounded-full flex items-center justify-center">
                <span className="text-white font-rubik text-lg sm:text-xl font-bold">P</span>
              </div>
              <h1 className="text-xl sm:text-2xl font-bold" style={{ fontFamily: "'Integral CF', sans-serif" }}>Peek</h1>
            </div>

            <div className="flex items-center gap-2">
              <LanguageSelector />
              <Button
                onClick={() => navigate('/create')}
                variant="outline"
                size="sm"
                className="gap-2 border-coral hover:bg-coral/10"
              >
                <Plus className="h-4 w-4" />
                <span className="hidden sm:inline">{t('home.header.create_sticker')}</span>
              </Button>
              {isDevMode && (
                <Button
                  onClick={handleCreateTestCommunity}
                  variant="outline"
                  size="sm"
                  className="gap-2 border-coral hover:bg-coral/10"
                >
                  <MapPin className="h-4 w-4" />
                  <span className="hidden sm:inline">Dev Test</span>
                </Button>
              )}
              <UserIdentityButton />
            </div>
          </div>
        </div>
      </header>

      {/* Rejoin Message */}
      {rejoinMessage && (
        <div className="container mx-auto px-4 pt-4">
          <Alert className="border-peach bg-peach/10">
            <MapPin className="h-4 w-4 text-coral" />
            <AlertDescription className="text-navy">
              {rejoinMessage}
              <Button
                size="sm"
                variant="link"
                className="ml-2 p-0 h-auto text-coral hover:text-coral/70"
                onClick={() => setRejoinMessage(null)}
              >
                Dismiss
              </Button>
            </AlertDescription>
          </Alert>
        </div>
      )}

      {/* Main Content */}
      <main className="container mx-auto px-3 sm:px-4 py-3 sm:py-4">
        {/* My Communities Section */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-rubik font-bold" style={{ fontSize: '1.25rem' }}>
              {t('home.my_communities.title')}
            </h2>
            <Badge className="bg-coral/10 text-coral border-0 px-3 py-1">
              {t('home.my_communities.count_joined', { count: communities.length })}
            </Badge>
          </div>

          {loading ? (
            <Card className="bg-card border-0 shadow-lg">
              <CardContent className="flex items-center justify-center py-12">
                <Loader2 className="h-8 w-8 animate-spin text-coral" />
              </CardContent>
            </Card>
          ) : communities.length === 0 ? (
            <Card className="bg-card border-0 shadow-lg">
              <CardContent className="text-center py-12">
                <div className="max-w-sm mx-auto space-y-4">
                  <div className="w-24 h-24 bg-coral/10 rounded-full flex items-center justify-center mx-auto">
                    <MapPin className="h-12 w-12 text-coral" />
                  </div>
                  <div>
                    <h3 className="text-xl font-rubik font-bold mb-2">
                      {t('home.my_communities.empty_title')}
                    </h3>
                    <p className="text-muted-foreground mb-6">
                      {t('home.my_communities.empty_message')}
                    </p>
                  </div>

                  <Alert className="text-left bg-mint/10 border-mint/20 dark:bg-mint/20 dark:border-mint/30">
                    <Crown className="h-4 w-4 text-mint" />
                    <AlertDescription className="dark:text-foreground">
                      {t('home.my_communities.pro_tip')}
                    </AlertDescription>
                  </Alert>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
              {communities.map((community) => (
                <Card
                  key={community.communityId}
                  className="cursor-pointer bg-card hover:shadow-xl transition-all duration-200 border-0 shadow-md overflow-hidden group"
                  onClick={() => handleCommunityClick(community.communityId)}
                >
                  <CardHeader className={`pb-3 relative h-32 overflow-hidden ${community.picture ? 'bg-gradient-to-br from-coral/20 to-peach/20' : 'bg-coral'}`}>
                    {/* Background Image */}
                    {community.picture && (
                      <div
                        className="absolute inset-0 bg-cover bg-center"
                        style={{ backgroundImage: `url(${community.picture})` }}
                      />
                    )}

                    {/* Gradient Overlay */}
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/70" />

                    {/* Content */}
                    <div className="relative h-full flex flex-col justify-between">
                      <div className="flex justify-end">
                        {community.isAdmin && (
                          <Badge className="bg-white text-coral border-0">
                            <Crown className="h-3 w-3 mr-1" />
                            {t('common.labels.founder')}
                          </Badge>
                        )}
                      </div>

                      <div className="flex-1" />

                      <div>
                        <CardTitle
                          className="font-bold line-clamp-1 text-white drop-shadow-lg"
                          style={{ fontFamily: "'Integral CF', sans-serif", fontSize: '1.25rem' }}
                        >
                          {community.name}
                        </CardTitle>
                        <CardDescription className="flex items-center gap-2 mt-1 text-white/90">
                          <Users className="h-3 w-3" />
                          <span>{t('home.my_communities.members_count', { count: community.memberCount })}</span>
                        </CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-3">
                    <div className="space-y-3">
                      {community.location && (
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <MapPin className="h-3 w-3" />
                          <span className="text-xs">
                            {t('home.my_communities.location_verified')}
                          </span>
                        </div>
                      )}

                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Clock className="h-3 w-3" />
                          <span>{t('home.my_communities.last_message', { time: formatTimeAgo(community.lastActivity || community.createdAt || community.joinedAt) })}</span>
                        </div>

                        {community.unreadCount && community.unreadCount > 0 && (
                          <Badge className="bg-coral text-white border-0 h-5 min-w-[20px] px-1">
                            {community.unreadCount}
                          </Badge>
                        )}
                      </div>

                      <Button
                        className="w-full bg-coral/10 hover:bg-coral hover:text-white text-coral transition-colors rounded-full font-semibold group-hover:bg-coral group-hover:text-white"
                        size="sm"
                      >
                        <MessageSquare className="h-4 w-4 mr-2" />
                        {t('home.my_communities.open_community')}
                        <ChevronRight className="h-4 w-4 ml-auto" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;