name: Build Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PWA Client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/pwa-client/Dockerfile
          push: true
          tags: |
            ghcr.io/verse-pbc/peek-pwa-client:latest
            ghcr.io/verse-pbc/peek-pwa-client:${{ github.sha }}
          build-args: |
            VITE_RELAY_URL=wss://communities2.nos.social
            VITE_VALIDATION_SERVICE_PUBKEY=npub1de8w8ur3drv89rtezsw0j32hq4wvv05qarsrdvxw75vvp9w35zdswz2tsq
            VITE_DEV_MODE=false
            VITE_FIREBASE_API_KEY=AIzaSyBh7apbudr8p4sAkaV22YqhofYLE3VrQo8
            VITE_FIREBASE_AUTH_DOMAIN=peek-afe3d.firebaseapp.com
            VITE_FIREBASE_PROJECT_ID=peek-afe3d
            VITE_FIREBASE_STORAGE_BUCKET=peek-afe3d.firebasestorage.app
            VITE_FIREBASE_MESSAGING_SENDER_ID=784762775027
            VITE_FIREBASE_APP_ID=1:784762775027:web:3fcfca122fc107d2655e86
            VITE_FIREBASE_VAPID_KEY=BJqaEQtkAj3PmdQ7iHleib_fA9Fpu4v5nPqGm-tw4AjS8HTOcGvsqjhhSHJo-S3Dp-zpQNyOj1uAxHLjuWsyJTw
            VITE_PUSH_SERVICE_NPUB=npub1nel9egkn5rjvdl4rw9udq7ptzawryuxjd54k7t7c6glr2g3fhsrstf9rj8
            VITE_APP_NAME=peek

      - name: Build and push Validation Service
        uses: docker/build-push-action@v5
        with:
          context: ./packages/validation-service
          file: ./packages/validation-service/Dockerfile
          push: true
          tags: |
            ghcr.io/verse-pbc/peek-validation-service:latest
            ghcr.io/verse-pbc/peek-validation-service:${{ github.sha }}